version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    ports:
      - "5432:5432"
  server:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - postgres