version: '3.5'

services:
  authorization-app:
    container_name: authorization-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USERNAME: "users"
      DB_PASSWORD: "dolganoffadmin"
    networks:
      - default
  db:
    container_name: db
    build:
      context: ./sql
      dockerfile: db.Dockerfile
    restart: always
    image: postgres:14
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "dolganoffadmin"
      POSTGRES_PASSWORD: "dolganoffadmin"
      POSTGRES_DB: "users"
    networks:
      - default
networks:
  default: {}