FROM golang:1.18 AS builder
WORKDIR /build

COPY cmd /build/cmd
COPY apis /build/apis
COPY config /build/config
COPY database /build/database
COPY utilities /build/utilities
COPY go.mod go.sum /build/

RUN go build -o authorizationGolang

FROM alpine:latest AS server

COPY --from=builder /build/authorizationGolang
COPY --from=builder /build/
COPY --from=builder /build/
COPY --from=builder /build/
COPY --from=builder /build/
COPY --from=builder /build/



CMD ["./authorizationGolang"]