FROM golang:1.18 as builder
WORKDIR /build

COPY cmd /build/cmd
COPY apis /build/apis
COPY config /build/config
COPY database /build/database
COPY utilities /build/utilities
COPY go.mod go.sum /build/

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main ./cmd/app/main.go

FROM alpine:3.16 as server
RUN apk add --no-cache

COPY --from=builder /build/main /app/

WORKDIR /app

CMD ["./main", "--c"]