FROM golang:1.18 AS builder
WORKDIR /build

COPY cmd /build/cmd
COPY apis /build/apis
COPY config /build/config
COPY database /build/database
COPY utilities /build/utilities
COPY go.mod go.sum /build/

RUN go version




RUN go mod download
RUN go build -o authorizationGolang ./cmd/main.go

CMD ["./authorizationGolang"]