FROM golang:1.18 as builder
WORKDIR /build

COPY cmd /build/cmd
COPY apis /build/apis
COPY config /build/config
COPY database /build/database
COPY utilities /build/utilities
COPY go.mod go.sum /build/

RUN GOOS=linux go build -o main ./cmd/main.go

FROM alpine:3.16 as server
RUN apk add --no-cache

COPY --from=builder /build/main /app/

WORKDIR /app

CMD ["./main", "--c"]