version: '3.5'

services:
  authorization-app:
    container_name: authorization-app
    build: ./
    ports:
      - 5000:5000
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "users"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "users"
